const Pool = require('pg').Pool;

const pool = new Pool({
    user: "postgres",
    password: "postgres", //add your password
    database: "homework4", // add your database name
    host: "localhost",
    port: "5432"
});

const execute = async(query) => {
    try {
        await pool.connect();
        await pool.query(query);
        return true;
    } catch (error) {
        console.error(error.stack);
        return false;
    }
};

const createTblQuery = `
    CREATE TABLE IF NOT EXISTS "users" (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        email VARCHAR(200) NOT NULL UNIQUE,
        password VARCHAR(200) NOT NULL 
    );
    CREATE TABLE IF NOT EXISTS "posts" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id uuid NOT NULL,
        title varchar(20) NOT NULL,
        timestamp timestamp NOT NULL DEFAULT NOW(),
        content varchar(200) NOT NULL,
        imgURL varchar(200)
    );`;

execute(createTblQuery).then(result => {
    if (result) {
        console.log('Table "users" is created');
    }
});

module.exports = pool;